modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="neo"
version="0.0.1"
displayName="Not Enough Ores"
logoFile="logo.png"
credits="Thanks to all who help me make this mod"
authors="JerryDoesModding"
description='''

'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
